#!/usr/bin/env python3
"""
Closed-Positions Dashboard - Data Builder
==========================================
Reads data/closed_positions.csv (your trade log) and notes/*.md (your
research notes), auto-computes P&L / sector / theme breakdowns and an
equity curve, and writes data/live.json for the dashboard to render.

You only ever hand-edit:
  - data/closed_positions.csv   Ticker, Shares, EntryDate, EntryPrice,
                                 CloseDate, ClosePrice, Theme
  - notes/*.md                  one file per research note, with a small
                                 frontmatter header (see notes/2026-03-10-nvda.md
                                 for the format)

Everything else -- Sector (looked up live), Status, P&L $/%, holding
days, the equity curve, sector/theme distribution, and note ordering --
is generated by this script. Sector is the only thing that comes from a
real data source; Theme stays a field you fill in yourself, since it's
your own thesis/classification and nothing can infer that from price data.

Run manually:
    python scripts/update_data.py

Normally triggered automatically by .github/workflows/update.yml whenever
you push a change to data/closed_positions.csv or notes/.
"""
import csv
import json
import re
import sys
from datetime import datetime
from pathlib import Path

import markdown as md
import yfinance as yf

ROOT = Path(__file__).resolve().parent.parent
POSITIONS_CSV = ROOT / "data" / "closed_positions.csv"
NOTES_DIR = ROOT / "notes"
LIVE_JSON = ROOT / "data" / "live.json"

DATE_FMT = "%Y-%m-%d"


def parse_date(s: str) -> datetime:
    return datetime.strptime(s.strip(), DATE_FMT)


def load_positions():
    if not POSITIONS_CSV.exists():
        print(f"[fatal] {POSITIONS_CSV} not found.", file=sys.stderr)
        sys.exit(1)
    rows = []
    with open(POSITIONS_CSV, newline="") as f:
        for row in csv.DictReader(f):
            ticker = (row.get("Ticker") or "").strip().upper()
            if not ticker:
                continue
            rows.append({
                "ticker": ticker,
                "shares": float(row["Shares"]),
                "entry_date": row["EntryDate"].strip(),
                "entry_price": float(row["EntryPrice"]),
                "close_date": row["CloseDate"].strip(),
                "close_price": float(row["ClosePrice"]),
                "theme": (row.get("Theme") or "").strip() or "Untagged",
            })
    return rows


_sector_cache = {}


def fetch_sector(ticker: str) -> str:
    """One lookup per ticker per run (cached in-memory) -- closed trades
    don't need live prices, just a sector classification."""
    if ticker in _sector_cache:
        return _sector_cache[ticker]
    sector = "Unknown"
    try:
        info = yf.Ticker(ticker).info
        sector = info.get("sector") or "Unknown"
    except Exception as exc:
        print(f"  [warn] {ticker}: sector lookup failed ({exc})", file=sys.stderr)
    _sector_cache[ticker] = sector
    return sector


def build_trades(positions):
    trades = []
    for p in positions:
        print(f"  processing {p['ticker']} ...")
        cost_basis = p["shares"] * p["entry_price"]
        proceeds = p["shares"] * p["close_price"]
        pl = proceeds - cost_basis
        pl_pct = (pl / cost_basis * 100) if cost_basis else None
        holding_days = (parse_date(p["close_date"]) - parse_date(p["entry_date"])).days
        sector = fetch_sector(p["ticker"])

        trades.append({
            **p,
            "sector": sector,
            "status": "Closed",
            "cost_basis": round(cost_basis, 2),
            "proceeds": round(proceeds, 2),
            "pl": round(pl, 2),
            "pl_pct": round(pl_pct, 2) if pl_pct is not None else None,
            "holding_days": holding_days,
        })

    trades.sort(key=lambda t: parse_date(t["close_date"]))
    for i, t in enumerate(trades, start=1):
        t["trade_num"] = i
    return trades


def build_equity_curve(trades):
    """Cumulative ADDITIVE P&L% -- each trade's return is simply added to
    the running total (not compounded/reinvested). Starts at 0% before
    any trades. E.g. +10%, -3%, +20% -> running total ends at +27%."""
    curve = [{"trade_num": 0, "equity_pct": 0.0}]
    running_total = 0.0
    for t in trades:
        if t["pl_pct"] is None:
            continue
        running_total += t["pl_pct"]
        curve.append({"trade_num": t["trade_num"], "equity_pct": round(running_total, 2)})
    return curve


def build_breakdown(trades, key):
    """Distribution by TICKER COUNT, not capital deployed -- each ticker
    contributes equally to its sector/theme bucket regardless of position
    size. E.g. one Tech ticker + one Healthcare ticker = 50/50, even if
    one position was 10x the dollar size of the other."""
    buckets = {}
    total = 0
    for t in trades:
        buckets[t[key]] = buckets.get(t[key], 0) + 1
        total += 1
    return [
        {"label": k, "value": v, "pct": round(v / total * 100, 2) if total else 0}
        for k, v in sorted(buckets.items(), key=lambda kv: -kv[1])
    ]


def parse_note(path: Path):
    """Minimal frontmatter parser: a --- delimited block of key: value
    lines at the top of the file, followed by a markdown body.

    Optional frontmatter field `pdf: filename.pdf` attaches a downloadable
    PDF (the file itself should be uploaded to notes/pdfs/filename.pdf).
    The markdown body can be left empty if the PDF is the whole note."""
    text = path.read_text(encoding="utf-8")
    meta = {"ticker": "", "date": "", "title": path.stem, "pdf": ""}
    body = text

    m = re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)$", text, re.DOTALL)
    if m:
        header, body = m.group(1), m.group(2)
        for line in header.splitlines():
            if ":" in line:
                k, v = line.split(":", 1)
                meta[k.strip().lower()] = v.strip()

    pdf_filename = meta.get("pdf", "").strip()

    return {
        "ticker": meta.get("ticker", "").strip().upper(),
        "date": meta.get("date", "").strip(),
        "title": meta.get("title", path.stem).strip(),
        "html": md.markdown(body.strip(), extensions=["extra"]) if body.strip() else "",
        "pdf_path": f"notes/pdfs/{pdf_filename}" if pdf_filename else None,
        "pdf_name": pdf_filename or None,
    }


def build_notes():
    if not NOTES_DIR.exists():
        return []
    notes = []
    for path in sorted(NOTES_DIR.glob("*.md")):
        if path.name.startswith("_"):
            continue  # convention: a leading underscore = template, skip it
        try:
            notes.append(parse_note(path))
        except Exception as exc:
            print(f"  [warn] {path.name}: failed to parse ({exc})", file=sys.stderr)

    def sort_key(n):
        try:
            return parse_date(n["date"])
        except Exception:
            return datetime.min

    notes.sort(key=sort_key, reverse=True)  # most recent first
    return notes


def main():
    positions = load_positions()
    print(f"Loaded {len(positions)} closed positions from {POSITIONS_CSV}")

    trades = build_trades(positions)
    equity_curve = build_equity_curve(trades)
    sector_breakdown = build_breakdown(trades, "sector")
    theme_breakdown = build_breakdown(trades, "theme")
    notes = build_notes()
    print(f"Loaded {len(notes)} research notes from {NOTES_DIR}")

    wins = [t for t in trades if t["pl_pct"] is not None and t["pl_pct"] > 0]
    win_rate = round(len(wins) / len(trades) * 100, 1) if trades else None

    LIVE_JSON.parent.mkdir(parents=True, exist_ok=True)
    with open(LIVE_JSON, "w") as f:
        json.dump({
            "updated": datetime.utcnow().isoformat(timespec="seconds") + "Z",
            "trades": trades,
            "equity_curve": equity_curve,
            "sector_breakdown": sector_breakdown,
            "theme_breakdown": theme_breakdown,
            "notes": notes,
            "summary": {
                "total_trades": len(trades),
                "win_rate": win_rate,
            },
        }, f, indent=2)
    print(f"Wrote {LIVE_JSON}")


if __name__ == "__main__":
    main()
